[package]
name = "vault"
version = "1.0.0"
edition = "2021"
authors = ["Dominik Wilkowski <Hi@Dominik-Wilkowski.com>", "Joshua Padman <joshua@padman.id.au>"]
license = "GPL-3.0-or-later"
description = "A vault GUI for your offline passwords"
homepage = "https://github.com/dominikwilkowski/vault"
repository = "https://github.com/dominikwilkowski/vault"
documentation = "https://docs.rs/vault/"
keywords = ["macos", "linux", "windows", "vault", "passwords"]
categories = ["cryptography", "database", "gui"]

[dependencies]
chrono = "0.4"
floem = { features = ["editor"], git = "https://github.com/lapce/floem.git", rev = "3c5cacbd2387f8ed9f0bdd5af3df587c26e3a084" }
im = "15.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
base64 = "0.22"
aes-gcm-siv = { version="0.11", features = ["std"] }
argon2 = { version="0.5", features = ["std", "zeroize"] }
webbrowser = "0.8"
url-escape = "0.1"
thiserror = "1.0"
crypto-common = "0.1"
anyhow = "1.0"
parking_lot = { version = "0.12" , features = ["deadlock_detection", "hardware-lock-elision"]}
zeroize = "1.7"
rand = { version = "0.8", features = ["getrandom"] }
sha2 = "0.10"

[dev-dependencies]
