[package]
name = "vault"
version = "1.0.0"
edition = "2021"
authors = ["Dominik Wilkowski <Hi@Dominik-Wilkowski.com>"]
license = "GPL-3.0-or-later"
description = "A vault GUI for your air-gaped passwords"
homepage = "https://github.com/dominikwilkowski/vault"
repository = "https://github.com/dominikwilkowski/vault"
documentation = "https://docs.rs/vault/"
keywords = ["GUI", "macos", "linux", "windows", "vault", "passwords"]
categories = ["cryptography", "database", "gui"]

[dependencies]
chrono = "0.4.31"
floem = { git = "https://github.com/lapce/floem.git", rev = "b4b5a19b1b4ee78188d3037fa5f9ad8ee5247d3b" }
im = "15.1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.8"
base64 = "0.21.5"
aes-gcm-siv = "0.11.1"
argon2 = "0.5.2"
webbrowser = "0.8.12"
url-escape = "0.1.1"

[dev-dependencies]
