[package]
name = "vault"
version = "1.0.0"
edition = "2021"
authors = ["Dominik Wilkowski <Hi@Dominik-Wilkowski.com>"]
license = "GPL-3.0-or-later"
description = "A vault GUI for your air-gaped passwords"
homepage = "https://github.com/dominikwilkowski/vault"
repository = "https://github.com/dominikwilkowski/vault"
documentation = "https://docs.rs/vault/"
keywords = ["GUI", "macos", "linux", "windows", "vault", "passwords"]
categories = ["cryptography", "database", "gui"]

[dependencies]
floem = { git = "https://github.com/lapce/floem.git", rev = "1a7a9f4e980be1edc5fcd27afb85d0bfbf524eed" }
im = "15.1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.8"

[dev-dependencies]
