[package]
name = "vault"
version = "1.0.0"
edition = "2021"
authors = ["Dominik Wilkowski <Hi@Dominik-Wilkowski.com>"]
license = "GPL-3.0-or-later"
description = "A vault GUI for your air-gaped passwords"
homepage = "https://github.com/dominikwilkowski/vault"
repository = "https://github.com/dominikwilkowski/vault"
documentation = "https://docs.rs/vault/"
keywords = ["GUI", "macos", "linux", "windows", "vault", "passwords"]
categories = ["cryptography", "database", "gui"]

[dependencies]
chrono = "0.4.31"
floem = { git = "https://github.com/lapce/floem.git", rev = "ac3654547948b600bc00ea62ce91fe4498d24f2f" }
im = "15.1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.8"
base64 = "0.21.5"
aes-gcm-siv = "0.11.1"
argon2 = "0.5.2"

[dev-dependencies]
