[general]
something = true
db_timeout = 900.0

[db]
encrypted = false
salt = "I'm making a note here: HUGE SUCCESS"
cypher = """
[[contents]]
id = 1
title = \"Bank\"
url = \"https://bankofaustralia.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents.fields]]
id = 1
title = \"Other\"
visible = true
value = [[1702851212, \"Some other notes\"]]

[[contents]]
id = 2
title = \"Google Account\"
url = \"https://Google Account.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 5
title = \"Facebook Login\"
url = \"https://Facebook Login.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 6
title = \"Amazon Password\"
url = \"https://Amazon Password.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 7
title = \"Twitter Access\"
url = \"https://Twitter Access.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 8
title = \"LinkedIn Credentials\"
url = \"https://LinkedIn Credentials.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 10
title = \"Microsoft Account\"
url = \"https://Microsoft Account.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 11
title = \"Instagram Secure Key\"
url = \"https://Instagram Secure Key.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 12
title = \"Dropbox Passcode\"
url = \"https://Dropbox Passcode.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 13
title = \"GitHub Authentication\"
url = \"https://GitHub Authentication.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 14
title = \"Netflix Login\"
url = \"https://Netflix Login.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 15
title = \"Apple ID Password\"
url = \"https://Apple ID Password.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 16
title = \"Spotify Access Code\"
url = \"https://Spotify Access Code.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 17
title = \"PayPal Secure Key\"
url = \"https://PayPal Secure Key.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 18
title = \"Reddit Credentials\"
url = \"https://Reddit Credentials.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 20
title = \"Airbnb Login\"
url = \"https://Airbnb Login.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 21
title = \"Office 365 Password\"
url = \"https://Office 365 Password.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 22
title = \"Evernote Secure Code\"
url = \"https://Evernote Secure Code.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 23
title = \"Tumblr Access\"
url = \"https://Tumblr Access.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 24
title = \"Pinterest Passphrase\"
url = \"https://Pinterest Passphrase.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 25
title = \"Skype Authentication\"
url = \"https://Skype Authentication.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 26
title = \"WhatsApp Secure Key\"
url = \"https://WhatsApp Secure Key.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 27
title = \"Snapchat Password\"
url = \"https://Snapchat Password.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 28
title = \"Zoom Login\"
url = \"https://Zoom Login.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 29
title = \"Slack Access Code\"
url = \"https://Slack Access Code.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 30
title = \"Uber Secure Key\"
url = \"https://Uber Secure Key.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 32
title = \"LastPass Master Password\"
url = \"https://LastPass Master Password.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 33
title = \"1Password Master Key\"
url = \"https://1Password Master Key.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 34
title = \"Dashlane Access\"
url = \"https://Dashlane Access.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 35
title = \"Keeper Security Code\"
url = \"https://Keeper Security Code.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 36
title = \"Bitwarden Password\"
url = \"https://Bitwarden Password.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 37
title = \"RoboForm Master Key\"
url = \"https://RoboForm Master Key.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents.fields]]
id = 3
title = \"Another note\"
visible = true
value = [[1702851212, \"Moar notes!!!\"]]

[[contents.fields]]
id = 4
title = \"Hidden\"
visible = false
value = [[1702851212, \"don't show me\"]]

[[contents]]
id = 38
title = \"Password Manager Master Password\"
url = \"https://Password Manager Master Password.com.au\"
username = [[1702851212, \"Dom\"]]
password = [[1702851212, \"totally_secure_password!1\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents]]
id = 41
title = \"Shopify\"
url = \"https://shopify.com\"
username = [[1702851212, \"Foo\"], [1702851212, \"Bar\"], [1702851212, \"Foobar\"], [1702851212, \"user1\"], [1702851212, \"user2\"], [1702851212, \"user3\"], [1702851212, \"user4\"], [1702851212, \"user5\"], [1702851212, \"user6\"], [1702851212, \"user7\"], [1702851212, \"user8\"], [1702851212, \"user9\"], [1702851212, \"user10\"], [1702851212, \"Dom\"], [1702851212, \"wizzy\"]]
password = [[1702851212, \"a_really_long_password_with spaces and stuff but most importantly very very long\"], [1702851212, \"totally_secure_password!1\"], [1702851212, \"totally_secure_password!2\"], [1702851212, \"totally_secure_password!3\"]]

[[contents.fields]]
id = 0
title = \"Notes\"
visible = true
value = [[1702851212, \"My secret notes\"]]

[[contents.fields]]
id = 1
title = \"Other\"
visible = true
value = [[1702851212, \"My other notes\"], [1702851212, \"My other notes\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"], [1702851212, \"stuff\"]]

[[contents.fields]]
id = 3
title = \"More\"
visible = true
value = [[1702851212, \"Moar\"]]

[[contents.fields]]
id = 7
title = \"Hidden field1\"
visible = false
value = [[1702851212, \"HIDDEN!!!!\"]]

[[contents.fields]]
id = 8
title = \"Hidden field2\"
visible = false
value = [[1702851212, \"HIDDEN!!!!\"]]

[[contents.fields]]
id = 9
title = \"Hidden field3\"
visible = false
value = [[1702851212, \"HIDDEN!!!!\"], [1702851212, \"HIDDEN!!!!!!\"], [1702851212, \"HIDDEN!!!!!!!!\"], [1702851212, \"HIDDEN!!!!!!!!!!!\"]]

[[contents.fields]]
id = 10
title = \"Last\"
visible = true
value = [[1702851212, \"Last notes\"], [1702851212, \"Really last notes\"]]
"""
